### ISSUE TITLE
Error when disconnecting multiple displays (multihead -> local)

### ISSUE THREAD

**Issue by ingmarlehmann** [symmsaur/screenorder#3]
HTR:
- 1. Connect multiple external screens
- 2. Run screenorder
- 3. Disconnect the screens
- 4. Run screenorder

After step 4, with my setup, I get the following error printout:

```
Running "xrandr --fb 1920x1080 --output DP-6 --mode 1920x1080 --panning 1920x1080+0+0 --pos 0x0 --output DP-0 --off --output DP-4 --off --output DP-2 --off --output DP-4.2.2.8 --off --output DP-3 --off --output DP-5 --off --output DP-1 --off"
xrandr: specified screen 1920x1080 not large enough for output DP-4.2.2.1 (1920x1200+3840+0)
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  21 (RRSetCrtcConfig)
  Serial number of failed request:  53
  Current serial number in output stream:  53
Traceback (most recent call last):
  File "/home/xxxxxxxx/.local/bin/screenorder", line 166, in <module>
    main()
  File "/home/xxxxxxxx/.local/bin/screenorder", line 161, in main
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['xrandr', '--fb', '1920x1080', '--output', 'DP-6', '--mode', '1920x1080', '--panning', '1920x1080+0+0', '--pos', '0x0', '--output', 'DP-0', '--off', '--output', 'DP-4', '--off', '--output', 'DP-2', '--off', '--output', 'DP-4.2.2.8', '--off', '--output', 'DP-3', '--off', '--output', 'DP-5', '--off', '--output', 'DP-1', '--off']' returned non-zero exit status 1.
```

Before running step 4 (after disconnecting the external monitors) the output of xrandr is:
```
Screen 0: minimum 8 x 8, current 5760 x 1200, maximum 32767 x 32767
DP-0 disconnected primary (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
DP-6 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.01*+
DP-4.2.2.8 disconnected 1920x1200+1920+0 (normal left inverted right x axis y axis) 0mm x 0mm
DP-4.2.2.1 disconnected 1920x1200+3840+0 (normal left inverted right x axis y axis) 0mm x 0mm
  1920x1200 (0x35c) 154.000MHz +HSync -VSync
        h: width  1920 start 1968 end 2000 total 2080 skew    0 clock  74.04KHz
        v: height 1200 start 1203 end 1209 total 1235           clock  59.95Hz
```

**Comment by symmsaur** [comment]
Could you please post results of `xrandr --verbose` before and after unplugging the monitors?

**Comment by ingmarlehmann** [comment]
[xrandr_multiple_monitors.txt](https://github.com/symmsaur/screenorder/files/10546064/xrandr_multiple_monitors.txt)
[xrandr_after_disconnect.txt](https://github.com/symmsaur/screenorder/files/10546066/xrandr_after_disconnect.txt)
[xrandr_after_disconnect_and_screenorder.txt](https://github.com/symmsaur/screenorder/files/10546068/xrandr_after_disconnect_and_screenorder.txt)
